/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recycleUI;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.AbstractListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;

import recycle.*;

import javax.swing.ListSelectionModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        funcPanel = new javax.swing.JPanel();
        add_btn = new javax.swing.JButton();
        remove_btn = new javax.swing.JButton();
        addItem_btn = new javax.swing.JButton();
        used_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        rcmPanel = new javax.swing.JPanel();
        rcmGroup_label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        scrolList = new javax.swing.JScrollPane();

        detailsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin-RMOS");

        funcPanel.setBackground(new java.awt.Color(255, 255, 255));
        funcPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        add_btn.setText("Add new machine");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        remove_btn.setText("Remove machine");
        remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_btnActionPerformed(evt);
            }
        });

        addItem_btn.setText("Add/Remove new item type");
        addItem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItem_btnActionPerformed(evt);
            }
        });

        used_btn.setText("Most used RCM");
        used_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                used_btnActionPerformed(evt);
            }
        });

        exit_btn.setText("EXIT");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        JButton btnNewButton = new JButton("New button");
        btnNewButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {

                setVisible(false);
                AdminUI2 admin2UI = new AdminUI2();
                admin2UI.setVisible(true);

            }
        });

        javax.swing.GroupLayout gl_funcPanel = new javax.swing.GroupLayout(funcPanel);
        gl_funcPanel
                .setHorizontalGroup(
                gl_funcPanel
                        .createParallelGroup(Alignment.TRAILING)
                        .addGroup(gl_funcPanel
                                .createSequentialGroup()
                                .addGroup(gl_funcPanel
                                        .createParallelGroup(Alignment.LEADING)
                                        .addGroup(gl_funcPanel
                                                .createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(gl_funcPanel
                                                        .createParallelGroup(Alignment.LEADING)
                                                        .addComponent(add_btn,
                                                                      GroupLayout.DEFAULT_SIZE,
                                                                      171,
                                                                      Short.MAX_VALUE)
                                                        .addComponent(remove_btn,
                                                                      GroupLayout.DEFAULT_SIZE,
                                                                      171,
                                                                      Short.MAX_VALUE)
                                                        .addComponent(addItem_btn,
                                                                      GroupLayout.DEFAULT_SIZE,
                                                                      171,
                                                                      Short.MAX_VALUE)))
                                        .addGroup(gl_funcPanel
                                                .createSequentialGroup()
                                                .addGap(52)
                                                .addComponent(exit_btn,
                                                              GroupLayout.DEFAULT_SIZE,
                                                              57, Short.MAX_VALUE)
                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                .addComponent(btnNewButton,
                                                              GroupLayout.PREFERRED_SIZE,
                                                              39,
                                                              GroupLayout.PREFERRED_SIZE)
                                                .addGap(50))
                                        .addGroup(gl_funcPanel
                                                .createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(used_btn,
                                                              GroupLayout.DEFAULT_SIZE,
                                                              171, Short.MAX_VALUE))
                                        .addGroup(gl_funcPanel.createSequentialGroup()
                                                .addContainerGap()
                                        ))
                                .addContainerGap())
                );
        gl_funcPanel.setVerticalGroup(
                gl_funcPanel.createParallelGroup(Alignment.LEADING)
                        .addGroup(gl_funcPanel.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(add_btn, GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addGap(18)
                                .addComponent(remove_btn, GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addGap(18)
                                .addComponent(addItem_btn, GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addGap(18)
                                .addComponent(used_btn, GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addGap(30)
                                .addGap(87)
                                .addGroup(gl_funcPanel.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(exit_btn, GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                        .addComponent(btnNewButton))
                                .addContainerGap())
                );
        funcPanel.setLayout(gl_funcPanel);

        rcmPanel.setBackground(new java.awt.Color(255, 255, 255));

        rcmGroup_label.setText("RCM Group");

        javax.swing.GroupLayout gl_rcmPanel = new javax.swing.GroupLayout(rcmPanel);
        rcmPanel.setLayout(gl_rcmPanel);
        gl_rcmPanel
                .setHorizontalGroup(
                gl_rcmPanel
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(gl_rcmPanel
                                .createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(gl_rcmPanel
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(gl_rcmPanel.createSequentialGroup()
                                                .addComponent(jSeparator1)
                                                .addGap(4, 4, 4))
                                        .addComponent(rcmGroup_label,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE))
                                .addGap(98, 98, 98))
                        .addGroup(gl_rcmPanel.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrolList)
                                .addGap(67, 67, 67))
                );
        gl_rcmPanel.setVerticalGroup(
                gl_rcmPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(gl_rcmPanel
                                .createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rcmGroup_label)
                                .addGap(13, 13, 13)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                              javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scrolList)
                                .addContainerGap())
                );

        String ID = "RCM ";

        rcmList = rmos1.getAllRecycleMachines();
        for (int i = 0; i < rcmList.size(); i++)
        {
            rcmNames[i] = ID + rcmList.get(i).getMachineId();

        }
        rcm_list = new javax.swing.JList<Object>(rcmNames);
        rcm_list.setVisibleRowCount(5);

        rcm_list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        scrolList.setViewportView(rcm_list);

        rcm_list.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {

                String itemDetails = "";
                selectedRCMName = (String) rcm_list.getSelectedValue();
                String selectedRCM = selectedRCMName.substring(4, selectedRCMName.length());
                macID = Integer.parseInt(selectedRCM);

                for (int i = 0; i < rcmList.size(); i++)
                {
                    String s = rcmList.get(i).getMachineId() + "";
                    if (s.equals(selectedRCM))
                    {
                        int numberofitems = rcmList.get(i).getNumberOfItems();
                        double money = rcmList.get(i).getTotalMoneyRemaining();
                        double totalw = rcmList.get(i).getTotalWeight();
                        double cashamt = rcmList.get(i).getTotalCashAmountRedeemed();
                        double capacity = rcmList.get(i).getAvailableCapacity();
                        Date date = rcmList.get(i).getLastTimeMachineEmptied();
                        OperationalStatus OperationalStatus = rcmList.get(i).getOperational();
                        itemDetails = "Machine ID:\t\t" + s + "\nNumber of items\t " +
                                rcmList.get(i).getNumberOfItems() +
                                "\nAvailable capacity:\t" + capacity + "\nLast emptied:\t\t" + date +
                                "\nOpretational status:\t" + OperationalStatus + "\t" + "\nTotal money remaining:\t" +
                                money + "\nTotal weight:\t\t" + totalw + "\nTotal cash amount redeemed\t" +
                                rcmList.get(i).getTotalCashAmountRedeemed();

                    }
                }

                RecycleMachineMonitor rm = new RecycleMachineMonitor();
                List<ItemType> as = rm.getItemTypesByMachineId(macID);
                String items = "";
                for (int i = 0; i < as.size(); i++)
                {
                    items = items + as.get(i).getName() + "  " + as.get(i).getPricePerLb() + "\n\t\t";
                }
                itemDetails = itemDetails + "\nItem Details:\t\t " + items;

                details_textArea.setText(itemDetails);

            }
        });

        detailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("RCM details");

        javax.swing.GroupLayout gl_detailsPanel = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(gl_detailsPanel);
        gl_detailsPanel
                .setHorizontalGroup(
                gl_detailsPanel
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addGroup(gl_detailsPanel
                                .createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(gl_detailsPanel
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2)
                                        .addComponent(jLabel2,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE))
                                .addGap(82, 82, 82))
                );
        gl_detailsPanel.setVerticalGroup(
                gl_detailsPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(gl_detailsPanel
                                .createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                              javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2)
                                .addContainerGap())
                );

        details_textArea = new javax.swing.JTextArea();
        details_textArea.setEditable(false);
        jScrollPane2.setViewportView(details_textArea);
        details_textArea.setBackground(new java.awt.Color(0, 0, 0));
        details_textArea.setColumns(20);
        details_textArea.setForeground(new java.awt.Color(255, 255, 255));
        details_textArea.setRows(5);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(Alignment.TRAILING,
                                  layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(funcPanel, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                          .addPreferredGap(ComponentPlacement.RELATED)
                                          .addComponent(rcmPanel, GroupLayout.PREFERRED_SIZE, 184,
                                                        GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(ComponentPlacement.RELATED)
                                          .addComponent(detailsPanel, GroupLayout.PREFERRED_SIZE,
                                                        GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                          .addContainerGap())
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addComponent(detailsPanel, GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addComponent(funcPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rcmPanel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {
        NewMachineUI new_machine = new NewMachineUI();
        //setVisible(true);
        new_machine.setVisible(true);
    }

    private void remove_btnActionPerformed(java.awt.event.ActionEvent evt) {
        //String rcm_remove=(String) rcm_list.getSelectedValue();
        rmos1.RemoveRecycleMachine(macID);
        JOptionPane.showMessageDialog(null, "RCM with RCM ID RCM" + macID + " is removed");
    }

    private void addItem_btnActionPerformed(java.awt.event.ActionEvent evt) {
        newItemTypeUI newItemsUI = new newItemTypeUI();
        // setVisible(false);
        newItemsUI.setVisible(true);
    }

    private void used_btnActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(null, "Most used is RCM 2");
    }

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {
        MainUI uiMain = new MainUI();
        setVisible(false);
        uiMain.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addItem_btn;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel rcmGroup_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList rcm_list;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel funcPanel;
    private javax.swing.JPanel rcmPanel;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JScrollPane scrolList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea details_textArea;
    private javax.swing.JButton remove_btn;
    private javax.swing.JButton used_btn;

    RecycleMachineMonitor rmos1 = new RecycleMachineMonitor();

    ArrayList<RecycleMachine> rcmList = new ArrayList<RecycleMachine>();
    String[] rcmNames = new String[10];
    static String selectedRCMName = new String();

    int macID;
}
