/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package recycleUI;

import java.util.ArrayList;
import java.util.List;

import recycle.ItemType;
import recycle.RecycleMachine;
import recycle.RecycleMachineMonitor;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.DefaultComboBoxModel;

public class newItemTypeUI extends javax.swing.JFrame {

    /**
     * Creates new form newItemTypeUI
     */
    public newItemTypeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        items_combo = new javax.swing.JComboBox();
        items_combo
                .setModel(new DefaultComboBoxModel(new String[] {"Aluminum", "Paper", "Bulb", "Wood", "Electronics"}));
        priceLb_label = new javax.swing.JLabel();
        price_field = new javax.swing.JTextField();
        addNew_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rcms_list = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        itemList_combo = new javax.swing.JComboBox();
        itemNames_label = new javax.swing.JLabel();
        remove_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add "));

        jLabel1.setText("ItemType");

        priceLb_label.setText("Price per lb");

        addNew_btn.setText("Add");
        addNew_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNew_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("RCM");

        rcms_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout
                .setHorizontalGroup(
                jPanel1Layout
                        .createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel1Layout
                                          .createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(jPanel1Layout
                                                            .createParallelGroup(Alignment.TRAILING)
                                                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 93,
                                                                          GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 64,
                                                                          GroupLayout.PREFERRED_SIZE))
                                          .addPreferredGap(ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                          .addGroup(jPanel1Layout
                                                            .createParallelGroup(Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout
                                                                              .createSequentialGroup()
                                                                              .addComponent(jLabel1,
                                                                                            GroupLayout.PREFERRED_SIZE,
                                                                                            60,
                                                                                            GroupLayout.PREFERRED_SIZE)
                                                                              .addGap(55))
                                                            .addGroup(jPanel1Layout
                                                                              .createSequentialGroup()
                                                                              .addComponent(items_combo,
                                                                                            GroupLayout.PREFERRED_SIZE,
                                                                                            89,
                                                                                            GroupLayout.PREFERRED_SIZE)
                                                                              .addGap(42)))
                                          .addGroup(jPanel1Layout
                                                            .createParallelGroup(Alignment.LEADING)
                                                            .addGroup(jPanel1Layout
                                                                              .createSequentialGroup()
                                                                              .addComponent(price_field, 57, 57, 57)
                                                                              .addGap(27)
                                                                              .addComponent(addNew_btn,
                                                                                            GroupLayout.PREFERRED_SIZE,
                                                                                            70,
                                                                                            GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(priceLb_label))
                                          .addGap(230))
                );
        jPanel1Layout
                .setVerticalGroup(
                jPanel1Layout
                        .createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel1Layout
                                          .createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(jPanel1Layout
                                                            .createParallelGroup(Alignment.BASELINE)
                                                            .addComponent(jLabel1)
                                                            .addComponent(priceLb_label)
                                                            .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE,
                                                                          GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                          .addPreferredGap(ComponentPlacement.RELATED)
                                          .addGroup(jPanel1Layout
                                                            .createParallelGroup(Alignment.LEADING)
                                                            .addGroup(jPanel1Layout
                                                                              .createSequentialGroup()
                                                                              .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(Alignment.BASELINE)
                                                                                                .addComponent(items_combo,
                                                                                                              GroupLayout.PREFERRED_SIZE,
                                                                                                              20,
                                                                                                              GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                  .createSequentialGroup()
                                                                                                                  .addGap(3)
                                                                                                                  .addComponent(price_field,
                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                                .addComponent(addNew_btn,
                                                                                                              GroupLayout.DEFAULT_SIZE,
                                                                                                              GroupLayout.DEFAULT_SIZE,
                                                                                                              Short.MAX_VALUE))
                                                                              .addGap(118))
                                                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE,
                                                                          141, GroupLayout.PREFERRED_SIZE)))
                );

        String ID = "RCM ";

        listOfRCM = rmos3.getAllRecycleMachines();
        for (int i = 0; i < listOfRCM.size(); i++)
        {
            namesOfRCM[i] = ID + listOfRCM.get(i).getMachineId();

        }
        rcms_list = new javax.swing.JList<Object>(namesOfRCM);
        //rcm_list.setVisibleRowCount(5);

        // rcm_list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(rcms_list);
        rcms_list.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {

                String itemDetails = "";
                selectedRCMName = (String) rcms_list.getSelectedValue();
                String selectedRCM = selectedRCMName.substring(4, selectedRCMName.length());
                macID = Integer.parseInt(selectedRCM);

                for (int i = 0; i < listOfRCM.size(); i++)
                {
                    String s = listOfRCM.get(i).getMachineId() + "";
                }
                List<ItemType> as = rmos3.getItemTypesByMachineId(macID);
                itemNames1 = new String[10];
                for (int i = 0; i < as.size(); i++)
                {
                    itemNames1[i] = as.get(i).getName();
                   
                }
                itemList_combo.setModel(new javax.swing.DefaultComboBoxModel(itemNames1));

            }
        });

        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove"));

        itemNames_label.setText("ItemType");

        remove_btn.setText("Remove");
        remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_btnActionPerformed(evt);
            }
        });

        JButton changePrice_btn = new JButton("Change Price");
        changePrice_btn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {

                String s = (String) itemList_combo.getSelectedItem();
                ItemType t = new ItemType(s, Double.parseDouble(textField.getText()));
                rmos3.updatePriceNew(macID, s, Double.parseDouble(textField.getText()));

                JOptionPane.showMessageDialog(null, "Price updated for the item");

            }
        });

        JLabel lblPricePerLb = new JLabel("Price per lb");

        textField = new JTextField();
        textField.setColumns(10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout
                .setHorizontalGroup(
                jPanel2Layout
                        .createParallelGroup(Alignment.LEADING)
                        .addGroup(Alignment.TRAILING,
                                  jPanel2Layout
                                          .createSequentialGroup()
                                          .addGroup(jPanel2Layout
                                                            .createParallelGroup(Alignment.LEADING)
                                                            .addGroup(jPanel2Layout
                                                                              .createSequentialGroup()
                                                                              .addGap(32)
                                                                              .addComponent(itemNames_label,
                                                                                            GroupLayout.DEFAULT_SIZE,
                                                                                            152, Short.MAX_VALUE)
                                                                              .addPreferredGap(ComponentPlacement.RELATED))
                                                            .addGroup(jPanel2Layout
                                                                              .createSequentialGroup()
                                                                              .addGap(21)
                                                                              .addComponent(itemList_combo,
                                                                                            GroupLayout.PREFERRED_SIZE,
                                                                                            109,
                                                                                            GroupLayout.PREFERRED_SIZE)
                                                                              .addGap(48)))
                                          .addGap(37)
                                          .addGroup(jPanel2Layout
                                                            .createParallelGroup(Alignment.TRAILING, false)
                                                            .addComponent(textField, 0, 0, Short.MAX_VALUE)
                                                            .addComponent(lblPricePerLb, GroupLayout.DEFAULT_SIZE,
                                                                          GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                          .addGap(39)
                                          .addComponent(remove_btn, GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                          .addGap(42)
                                          .addComponent(changePrice_btn)
                                          .addGap(23))
                );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel2Layout
                                          .createSequentialGroup()
                                          .addGap(21)
                                          .addGroup(jPanel2Layout
                                                            .createParallelGroup(Alignment.BASELINE)
                                                            .addComponent(itemNames_label, GroupLayout.DEFAULT_SIZE,
                                                                          17, Short.MAX_VALUE)
                                                            .addComponent(lblPricePerLb))
                                          .addPreferredGap(ComponentPlacement.RELATED)
                                          .addGroup(jPanel2Layout
                                                            .createParallelGroup(Alignment.BASELINE)
                                                            .addComponent(itemList_combo, GroupLayout.PREFERRED_SIZE,
                                                                          GroupLayout.DEFAULT_SIZE,
                                                                          GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(remove_btn, GroupLayout.PREFERRED_SIZE, 0,
                                                                          Short.MAX_VALUE)
                                                            .addComponent(changePrice_btn)
                                                            .addComponent(textField, GroupLayout.PREFERRED_SIZE,
                                                                          GroupLayout.DEFAULT_SIZE,
                                                                          GroupLayout.PREFERRED_SIZE))
                                          .addContainerGap(42, Short.MAX_VALUE))
                );
        jPanel2.setLayout(jPanel2Layout);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jPanel1,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          Short.MAX_VALUE)
                                                            .addComponent(jPanel2,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          Short.MAX_VALUE))
                                          .addContainerGap())
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                          .addGap(20, 20, 20)
                                          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(24, 24, 24)
                                          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addContainerGap())
                );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNew_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNew_btnActionPerformed
        String s = (String) items_combo.getSelectedItem();
        ItemType t = new ItemType(s, Double.parseDouble(price_field.getText()));
        rmos3.addnewItem(macID, s, Double.parseDouble(price_field.getText()));

        JOptionPane.showMessageDialog(null, "New Item type added");

    }//GEN-LAST:event_addNew_btnActionPerformed//

    private void remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_btnActionPerformed
        String s = (String) itemList_combo.getSelectedItem();
        rmos3.deleteItemType(macID, s);
        JOptionPane.showMessageDialog(null, "New Item deleted");
    }//GEN-LAST:event_remove_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newItemTypeUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                  ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newItemTypeUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                  ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newItemTypeUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                  ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newItemTypeUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                  ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newItemTypeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNew_btn;
    private javax.swing.JComboBox itemList_combo;
    private javax.swing.JLabel itemNames_label;
    private javax.swing.JComboBox items_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceLb_label;
    private javax.swing.JTextField price_field;
    private javax.swing.JList rcms_list;
    private javax.swing.JButton remove_btn;

    RecycleMachineMonitor rmos3 = new RecycleMachineMonitor();
    ArrayList<RecycleMachine> listOfRCM = new ArrayList<RecycleMachine>();
    String[] namesOfRCM = new String[10];
    String[] itemNames1;
    static String selectedRCMName = new String();

    int macID;
    private JTextField textField;
}
