/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package recycleUI;

import javax.swing.JOptionPane;

import recycle.*;
import javax.swing.JFrame;

public class NewMachineUI extends javax.swing.JFrame {

    /**
     * Creates new form NewMachineUI
     */
    public NewMachineUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        loc_field = new javax.swing.JTextField();
        amt_label = new javax.swing.JLabel();
        cap_field = new javax.swing.JTextField();
        loc_label = new javax.swing.JLabel();
        cap_label = new javax.swing.JLabel();
        initAmt_field = new javax.swing.JTextField();
        machineID_label = new javax.swing.JLabel();
        machineID_field = new javax.swing.JTextField();
        addRCM_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        items_comboBox = new javax.swing.JComboBox();
        price_field = new javax.swing.JTextField();
        iAccepted_label = new javax.swing.JLabel();
        putItem_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTextField2.setText("jTextField2");
        setTitle("New RCM");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter details"));

        amt_label.setText("Initial Amount");

        cap_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap_fieldActionPerformed(evt);
            }
        });

        loc_label.setText("Location");

        cap_label.setText("Capacity");

        machineID_label.setText("Machine ID");

        addRCM_btn.setText("ADD");
        addRCM_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRCM_btnActionPerformed(evt);
            }
        });

        clear_btn.setText("CLEAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout
                .setHorizontalGroup(
                jPanel2Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout
                                .createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(machineID_label,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                        .addComponent(loc_label,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                        .addComponent(cap_label,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                        .addComponent(amt_label,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE, 96,
                                                      Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                  jPanel2Layout
                                                          .createSequentialGroup()
                                                          .addComponent(addRCM_btn,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        77, Short.MAX_VALUE)
                                                          .addGap(18, 18, 18)
                                                          .addComponent(clear_btn,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                        .addComponent(cap_field)
                                        .addComponent(loc_field)
                                        .addComponent(machineID_field)
                                        .addComponent(initAmt_field,
                                                      javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(34, 34, 34))
                );
        jPanel2Layout
                .setVerticalGroup(
                jPanel2Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout
                                .createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(machineID_label,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                        .addComponent(machineID_field))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(loc_label,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                        .addComponent(loc_field))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cap_field)
                                        .addGroup(jPanel2Layout
                                                .createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cap_label,
                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                              Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(initAmt_field)
                                        .addComponent(amt_label,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addRCM_btn,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                        .addComponent(clear_btn,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE))
                                .addContainerGap())
                );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        items_comboBox
                .setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Aluminum", "Paper", "Bulb", "Wood"}));

        iAccepted_label.setText("Items accepted");

        putItem_btn.setText("Select");
        putItem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putItem_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout
                                .createSequentialGroup()
                                .addContainerGap()
                                .addComponent(iAccepted_label, javax.swing.GroupLayout.DEFAULT_SIZE,
                                              javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(items_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                              Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(price_field)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(putItem_btn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                              javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
        jPanel3Layout
                .setVerticalGroup(
                jPanel3Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout
                                          .createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(jPanel3Layout
                                                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(putItem_btn,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          Short.MAX_VALUE)
                                                            .addGroup(jPanel3Layout
                                                                              .createSequentialGroup()
                                                                              .addGap(3, 3, 3)
                                                                              .addGroup(jPanel3Layout
                                                                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(price_field)
                                                                                                .addComponent(iAccepted_label,
                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                              Short.MAX_VALUE)
                                                                                                .addComponent(items_comboBox))))
                                          .addContainerGap())
                );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                        .addComponent(jPanel2,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      Short.MAX_VALUE))
                                .addGap(142, 142, 142))
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                              javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                              javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(62, 62, 62))
                );

        pack();
    }// </editor-fold>                        

    private void cap_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addRCM_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRCM_btnActionPerformed
        machineID = Integer.parseInt(machineID_field.getText());
        String location = loc_field.getText();
        int capacity = Integer.parseInt(cap_field.getText());
        double initial_amt = Double.parseDouble(initAmt_field.getText());

        rmos.AddRecycleMachine(machineID, location, capacity, initial_amt, 0.0, true);

        JOptionPane.showMessageDialog(null, "RCM added successfully");
    }//GEN-LAST:event_addRCM_btnActionPerformed

    private void putItem_btnActionPerformed(java.awt.event.ActionEvent evt) {
        machineID = Integer.parseInt(machineID_field.getText());
        String items = (String) items_comboBox.getSelectedItem();
        ItemType itemType1 = new ItemType(items, Double.parseDouble(price_field.getText()));

        rmos.addRecycleItemType(machineID, itemType1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMachineUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                 ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMachineUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                 ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMachineUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                 ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMachineUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                 ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMachineUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addRCM_btn;
    private javax.swing.JLabel amt_label;
    private javax.swing.JTextField cap_field;
    private javax.swing.JLabel cap_label;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel iAccepted_label;
    private javax.swing.JTextField initAmt_field;
    private javax.swing.JComboBox items_comboBox;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField loc_field;
    private javax.swing.JLabel loc_label;
    private javax.swing.JTextField machineID_field;
    private javax.swing.JLabel machineID_label;
    private javax.swing.JTextField price_field;
    private javax.swing.JButton putItem_btn;

    int machineID;
    RecycleMachineMonitor rmos = new RecycleMachineMonitor();
    // End of variables declaration                   
}
